# version: '2'

# services:
#   zookeeper:
#     image: bitnami/zookeeper:latest
#     ports:
#       - "2181:2181"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes

#   kafka:
#     image: bitnami/kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#       - ALLOW_PLAINTEXT_LISTENER=yes

version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper


# docker-compose down    stop and remove containers
# docker-compose up -d   start containers in detached mode
# docker ps              list running containers


# docker-compose up -d  # docker-compose down


# docker exec -it kafka bash
# kafka-topics --create --topic saas-events \
#  --bootstrap-server localhost:9092 \
#  --partitions 1 \
#  --replication-factor 1

# kafka-topics --list --bootstrap-server localhost:9092

# docker exec -it kafka bash  


# kafka-console-consumer --bootstrap-server localhost:9092 \
#  --topic saas-events --from-beginning



# Running Kafka Console Producer

# docker-compose down -v
# docker-compose up -d

# Check Live or not 
# docker ps